version: '3.8'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  jmeter:
    image: justb4/jmeter:5.5
    volumes:
      - ./jmeter:/test
    working_dir: /test
    entrypoint: ["jmeter"]
    command: ["-n", "-t", "testplan.jmx"]

volumes:
  jenkins_home:
  pgdata:
