
--6) napisz selekty w plikach SQL albo w pythonie (jak wolisz):

--1) wszytkie mecze Wisly Kraków, z ostatniego miesiaca


--2)wszystkie mecze Lecha na wyjezdzie 


--3)wszystkie zwyciestwa Rakowa Czestochowa


--4)wszystkie porazki albo zwyciestwa Jagielonii u siebie 


--5)ostatnie 5 meczow Legii z Wisłą (dane  możesz dopisać do tabeli żeby ładnie było widać, ale  sam SELECT też wystarczy)


--6) historię wszystkich klubów założonych przed wojną :)